name: MyTeams actions
on:
  push:
    branches-ignore:
      - ga-ignore-**
env:
  MIRROR_URL:
    git@github.com:EpitechPromo2026/B-OOP-400-REN-4-1-raytracer-lucas.iglesia.git
  EXECUTABLES:
    "raytracer"

jobs:
  cleaning:
    name: Cleaning...
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

  compilation:
    name: Compiling...
    needs: cleaning
    runs-on: ubuntu-latest
    container: epitechcontent/epitest-docker
    timeout-minutes: 4
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: |
          make fclean
          echo make
          make clean

  mirroring:
    runs-on: ubuntu-latest
    needs: compilation
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            ${{ env.MIRROR_URL }}
          ssh_private_key:
            ${{ secrets.GITLAB_SSH_PRIVATE_KEY }}